name: ESLint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install node modules
        run: npm install
      - name: Run ESLint
        run: npm run eslint