name: Tests
on: [push]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootPassword
          MYSQL_DATABASE: dda_builds
        # map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run npm
        run: npm install

      - name: Run ESLint
        run: npm run eslint

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan dusk:install
          php artisan migrate:fresh
          chmod -R 0755 vendor/laravel/dusk/bin/
          npm run dev-hot > /dev/null 2>&1 &
          ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
          php artisan serve > /dev/null 2>&1 &
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: dda_builds
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: rootPassword
          APP_ENV: testing

      - name: Run phpunit
        run: ./vendor/bin/phpunit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: dda_builds
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: rootPassword
          APP_ENV: testing

      - name: Run browser tests
        run: php artisan dusk
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: dda_builds
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: rootPassword
          APP_ENV: testing

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Browser Screenshots
          path: ./tests/Browser/screenshots